//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestauranteEntities : DbContext
    {
        public RestauranteEntities()
            : base("name=RestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<camarero> camarero { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<consumicion> consumicion { get; set; }
        public virtual DbSet<itemconsumicion> itemconsumicion { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<mesa> mesa { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<productosmenu> productosmenu { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<tipoproducto> tipoproducto { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
