//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumicion
    {
        public int id { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
        public int servida { get; set; }
        public int pedido { get; set; }
        public int itemconsumicion { get; set; }
    
        public virtual itemconsumicion itemconsumicion1 { get; set; }
        public virtual pedido pedido1 { get; set; }
    }
}
