//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido()
        {
            this.consumicion = new HashSet<consumicion>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal precio { get; set; }
        public int pagado { get; set; }
        public int confirmado { get; set; }
        public int servido { get; set; }
        public int activo { get; set; }
        public int cliente { get; set; }
        public int mesa { get; set; }
        public int camarero { get; set; }
    
        public virtual camarero camarero1 { get; set; }
        public virtual cliente cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumicion> consumicion { get; set; }
        public virtual mesa mesa1 { get; set; }
    }
}
