//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int finalizada { get; set; }
        public int cliente { get; set; }
        public int mesa { get; set; }
    
        public virtual cliente cliente1 { get; set; }
        public virtual mesa mesa1 { get; set; }
    }
}
